### ISSUE TITLE
can you automatically exit the scan after its done without pressing enter?

### ISSUE THREAD

**Issue by rew1nter** [blacklanternsecurity/bbot#782]
can you automatically exit the scan after its done without pressing enter?

**Comment by TheTechromancer** [comment]
Yes, with `-y`.

**Comment by TheTechromancer** [comment]
@rew1nter I misunderstood your question. The pause you're referring to is a bug. We are working to fix it.

**Comment by rew1nter** [comment]
Yeah I was wondering why it's pausing at the end despite using `-y`. Please reply to this issue when this bug is fixed

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/788.

**Comment by rew1nter** [comment]
![image](https://github.com/blacklanternsecurity/bbot/assets/64508791/613083e5-bae7-4f77-a22b-bd71d90b22bd)

**Comment by rew1nter** [comment]
This issue persists. The scan is stuck here after its done. It exited after pressing enter.
![image](https://github.com/blacklanternsecurity/bbot/assets/64508791/89f85e83-da1c-4758-9ee2-058cb274300b)

the command I used `$ bbot -t domain.tld -f subdomain-enum -rf passive -om human -o /tmp/ -n my_scan -em massdns -y -s `

**Comment by TheTechromancer** [comment]
The fix hasn't made its way to `stable` yet. Can you make sure you have the `dev` branch installed?

```bash
# bleeding edge (dev branch)
pipx install --pip-args '\--pre' bbot
```

**Comment by rew1nter** [comment]
I uninstalled the previous version and installed it with your command. 

It still gets stuck at the end.

`$bbot -y -t domain.tld -f subdomain-enum -rf passive -om human -o /tmp/ -n my_scan -em massdns`
![image](https://github.com/blacklanternsecurity/bbot/assets/64508791/64194346-3f9e-4a40-9b63-e03b9e41abde)

**Comment by rew1nter** [comment]
Okay I repeated the process and the issue is resolved :)
